# Generated by Django 3.2 on 2021-06-25 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
        ('formulario', '0001_initial'),
        ('investigacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=30)),
                ('alumno_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estudiantes.alumno')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.encuesta')),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.evaluacion')),
                ('formula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='investigacion.formula')),
            ],
        ),
    ]
