# Generated by Django 3.2 on 2021-09-09 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
