# Generated by Django 3.2 on 2021-09-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='encuesta',
            field=models.IntegerField(default=0),
        ),
    ]
