# Generated by Django 3.2 on 2021-08-02 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210704_1919'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='estado',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='f_inicio',
            field=models.DateField(auto_now=True, verbose_name='fecha inicio'),
        ),
        migrations.AlterField(
            model_name='encuesta',
            name='tipo',
            field=models.CharField(default='version 1', max_length=30),
        ),
    ]
