# Generated by Django 3.2 on 2021-09-09 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alumno_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
