# Generated by Django 3.2 on 2021-09-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210902_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta',
            name='ponderado',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='respuesta',
            name='respuesta',
            field=models.CharField(default='', max_length=250),
        ),
    ]
