# Generated by Django 3.2 on 2021-08-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210801_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='estado',
            field=models.IntegerField(default=1),
        ),
    ]
