# Generated by Django 3.2 on 2021-09-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_historicalcategoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalcategoria',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
