# Generated by Django 3.2 on 2021-09-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210905_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termino',
            name='signo',
        ),
    ]
