# Generated by Django 3.2 on 2021-09-02 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210901_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='encuesta',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
