# Generated by Django 3.2 on 2021-09-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_termino_signo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignacion',
            name='completada',
            field=models.BooleanField(default=False),
        ),
    ]
