# Generated by Django 3.2 on 2021-08-04 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_pregunta_estado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opciones',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.pregunta',),
        ),
    ]
