# Generated by Django 3.2 on 2021-09-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_encuesta_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
