# Generated by Django 3.2 on 2021-08-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_opciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opciones',
        ),
        migrations.AddField(
            model_name='termino',
            name='variable',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='core.categoria'),
        ),
    ]
