# Generated by Django 3.2 on 2021-08-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_opciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Opciones',
        ),
    ]
