# Generated by Django 3.2 on 2021-09-07 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_asignacion_completada'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultado',
            name='puntaje',
            field=models.FloatField(default=0),
        ),
    ]
