# Generated by Django 3.2 on 2021-09-02 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210901_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrera',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='nivel',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='periodo',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tpregunta',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
