# Generated by Django 3.2 on 2021-09-02 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210901_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parametro',
            name='deleted',
        ),
        migrations.AddField(
            model_name='asignacion',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='estudio',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
