# Generated by Django 3.2 on 2021-09-02 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210901_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='enunciado',
            field=models.TextField(),
        ),
    ]
