# Generated by Django 3.2 on 2021-05-27 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encuesta',
            options={'verbose_name': 'Encuesta'},
        ),
    ]
