# Generated by Django 3.2 on 2021-05-27 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alter_encuesta_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encuesta',
            name='f_vigencia',
            field=models.DateTimeField(verbose_name='fecha vigencia'),
        ),
    ]
