# Generated by Django 3.2 on 2021-05-27 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_encuesta_f_vigencia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asignacion',
        ),
    ]
